#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

$CLASSPATH = "-cp bin:lib/antlr-4.1-complete.jar/"
$MAIN = "frontend.Main"
$INPUT = ARGV[0]

`java #$CLASSPATH #$MAIN #$INPUT`
